FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=4000

WORKDIR /app

RUN addgroup --system starter && \
          adduser --system -G starter starter

COPY ./dist/apps/starter .
COPY ./libs/graphql-lib/src/lib/schema.graphql .
COPY package.json .
COPY package-lock.json .
RUN chown -R starter:starter .

RUN npm install --omit=dev

CMD [ "node", "main.js" ]
